#!/bin/bash

echo "🎨 Fifi Hair Salon - Image Setup Helper"
echo "========================================"
echo ""
echo "This script will help you add the right images for your black women hair salon."
echo ""
echo "📁 Image directories created:"
echo "   - public/images/hero/ (for main portrait)"
echo "   - public/images/intro/ (for 3 intro grid images)"
echo "   - public/images/gallery/ (for 12 gallery images)"
echo "   - public/images/services/ (for 8 service images)"
echo ""
echo "📋 Next steps:"
echo "1. Get images from:"
echo "   - AI tools (DALL-E, Midjourney, Stable Diffusion)"
echo "   - Stock photos (Unsplash, Pexels)"
echo "   - Professional photographers"
echo ""
echo "2. Use the prompts in IMAGE_REQUIREMENTS.md"
echo ""
echo "3. Add images to the correct directories:"
echo "   - Hero: public/images/hero/portrait.jpg"
echo "   - Intro: public/images/intro/p1.jpg, p2.jpg, p3.jpg"
echo "   - Gallery: public/images/gallery/01.jpg through 12.jpg"
echo "   - Services: public/images/services/[service-name].jpg"
echo ""
echo "4. Make sure images are:"
echo "   - High quality (at least 400px wide)"
echo "   - Show black women with various hair styles"
echo "   - Professional salon setting"
echo "   - Warm, inviting lighting"
echo ""
echo "✨ Your website is ready at: http://localhost:3000"
echo "   (or http://localhost:3001 if port 3000 is busy)"
